# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b526bf44d8c715cbd9f94b1ce2b2f71365d36106da859f1b719e7bb8439123fd76fd41ed9faa3ee172c8f5734aeca246ee8a3191180787fb28ce07340cb6f2d

test:
  secret_key_base: 89fc3bee0a5cdfc0efc1d131ecb99972fa2a3c2eb32f4dbd921cd57eb3efa9d518276048c84431b7bef88294c2e14b1f749418cb788262be61986615766db53e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
